/**
 * Single source of truth for brand identity.
 * Change the name here and it propagates across the entire site.
 */
export const BRAND = {
  name: "PeptideCheckup",
  /** Two-word display form used in prose. */
  displayName: "Peptide Checkup",
  /** Wordmark split for two-tone logo rendering. */
  wordmark: { a: "Peptide", b: "Checkup" },
  domain: "peptidecheckup.com",
  /** Canonical origin. Overridable at build time (e.g. a preview host) via NEXT_PUBLIC_SITE_URL. */
  url: (process.env.NEXT_PUBLIC_SITE_URL ?? "https://peptidecheckup.com").replace(/\/+$/, ""),
  tagline: "Compare peptides. Check your fit.",
  description:
    "Evidence-led peptide comparison and a personalised health assessment that maps your goals, medical history and medications against the published research and regulatory status — so you know exactly what to discuss with a clinician.",
  shortDescription:
    "Evidence-led peptide comparison and a personalised suitability assessment.",
  supportEmail: "hello@peptidecheckup.com",
  social: {
    x: "https://x.com/peptidecheckup",
    instagram: "https://instagram.com/peptidecheckup",
    tiktok: "https://tiktok.com/@peptidecheckup",
  },
  /** Used in JSON-LD and metadata. */
  legalName: "PeptideCheckup Ltd",
  foundedYear: 2026,
} as const;

/** Shared social-preview image (1200×630) for every page's Open Graph / Twitter card. */
export const OG_IMAGES = [
  { url: `${BRAND.url}/og.png`, width: 1200, height: 630, alt: `${BRAND.displayName} — ${BRAND.tagline}` },
];

/** Standard disclaimer shown across the site and in every report. */
export const DISCLAIMER_SHORT =
  `${BRAND.displayName} provides educational information and a structured summary of published research and regulatory status. It is not medical advice, does not diagnose or treat any condition, and does not replace a consultation with a qualified healthcare professional.`;

export const DISCLAIMER_REPORT =
  "This report is generated by a deterministic, clinician-reviewable rules engine from the information you provided and our maintained compound, evidence and regulatory database. It does not recommend that you take any compound. Suitability labels describe whether your responses identified factors that warrant professional review — they are not a clinical determination. Always consult a qualified healthcare professional before starting, stopping or combining any medicine, peptide or supplement.";
