/**
 * Single source of truth for brand identity.
 * The store is the client's brand (AERVYN · Performance Science); the
 * assessment product keeps its own name ("Peptide Checkup").
 */
export const BRAND = {
  name: "AERVYN",
  /** Display form used in prose. */
  displayName: "Aervyn",
  /** Wordmark split around the helix glyph that replaces the "Y". */
  wordmark: { a: "AERV", b: "N" },
  descriptor: "Performance Science",
  /** Name of the assessment / quiz product. */
  assessmentName: "Peptide Checkup",
  domain: "aervyn.com",
  /** Canonical origin. Overridable at build time (e.g. a preview host) via NEXT_PUBLIC_SITE_URL. */
  url: (process.env.NEXT_PUBLIC_SITE_URL ?? "https://aervyn.com").replace(/\/+$/, ""),
  tagline: "Peptide pens. Matched to you.",
  description:
    "Aervyn peptide pens — pre-filled, dose-dial, batch-tested with a published certificate of analysis — matched to your goal by the 7-minute Peptide Checkup, which also tells you when not to buy.",
  shortDescription: "Batch-tested peptide pens, matched to your goal by the Peptide Checkup assessment.",
  supportEmail: "hello@aervyn.com",
  social: {
    x: "https://x.com/aervyn",
    instagram: "https://instagram.com/aervyn",
    tiktok: "https://tiktok.com/@aervyn",
  },
  /** Used in JSON-LD and metadata. */
  legalName: "Aervyn Ltd",
  foundedYear: 2025,
  /** Where the business operates from — drives default currency, jurisdiction and shipping copy. */
  homeCountry: "GB",
} as const;

/** Shared social-preview image (1200×630) for every page's Open Graph / Twitter card. */
export const OG_IMAGES = [
  { url: `${BRAND.url}/og.png`, width: 1200, height: 630, alt: `${BRAND.name} — ${BRAND.tagline}` },
];

/** Standard disclaimer shown across the site and in every report. */
export const DISCLAIMER_SHORT =
  `The ${BRAND.assessmentName} provides educational information and a structured summary of published research and regulatory status. It is not medical advice, does not diagnose or treat any condition, and does not replace a consultation with a qualified healthcare professional.`;

export const DISCLAIMER_REPORT =
  "This report is generated by a deterministic, clinician-reviewable rules engine from the information you provided and our maintained compound, evidence and regulatory database. It does not recommend that you take any compound. Suitability labels describe whether your responses identified factors that warrant professional review — they are not a clinical determination. Always consult a qualified healthcare professional before starting, stopping or combining any medicine, peptide or supplement.";

/** Labelling for products that are not authorised medicines. Shown on product pages, cart and checkout. */
export const RESEARCH_USE_LABEL =
  "Sold for research use only. Not a medicine and not authorised for human consumption. Purchasers must be 18+ and confirm intended use at checkout.";
