/**
 * Single source of truth for brand identity.
 * Change the name here and it propagates across the entire site.
 */
export const BRAND = {
  name: "PeptideCheckup",
  /** Two-word display form used in prose. */
  displayName: "Peptide Checkup",
  /** Wordmark split for two-tone logo rendering. */
  wordmark: { a: "Peptide", b: "Checkup" },
  domain: "peptidecheckup.com",
  /** Canonical origin. Overridable at build time (e.g. a preview host) via NEXT_PUBLIC_SITE_URL. */
  url: (process.env.NEXT_PUBLIC_SITE_URL ?? "https://peptidecheckup.com").replace(/\/+$/, ""),
  tagline: "Batch-tested peptides. Matched to you.",
  description:
    "Batch-tested peptides with a published certificate of analysis, plus a 7-minute assessment that maps your goal, history and medicines against the evidence — and tells you when not to buy.",
  shortDescription:
    "Batch-tested peptides with published certificates of analysis, matched to your goal by an evidence-led assessment.",
  supportEmail: "hello@peptidecheckup.com",
  social: {
    x: "https://x.com/peptidecheckup",
    instagram: "https://instagram.com/peptidecheckup",
    tiktok: "https://tiktok.com/@peptidecheckup",
  },
  /** Used in JSON-LD and metadata. */
  legalName: "PeptideCheckup Ltd",
  foundedYear: 2026,
  /** Where the business operates from — drives default currency, jurisdiction and shipping copy. */
  homeCountry: "GB",
} as const;

/** Shared social-preview image (1200×630) for every page's Open Graph / Twitter card. */
export const OG_IMAGES = [
  { url: `${BRAND.url}/og.png`, width: 1200, height: 630, alt: `${BRAND.displayName} — ${BRAND.tagline}` },
];

/** Standard disclaimer shown across the site and in every report. */
export const DISCLAIMER_SHORT =
  `${BRAND.displayName} provides educational information and a structured summary of published research and regulatory status. It is not medical advice, does not diagnose or treat any condition, and does not replace a consultation with a qualified healthcare professional.`;

export const DISCLAIMER_REPORT =
  "This report is generated by a deterministic, clinician-reviewable rules engine from the information you provided and our maintained compound, evidence and regulatory database. It does not recommend that you take any compound. Suitability labels describe whether your responses identified factors that warrant professional review — they are not a clinical determination. Always consult a qualified healthcare professional before starting, stopping or combining any medicine, peptide or supplement.";

/** Labelling for products that are not authorised medicines. Shown on product pages, cart and checkout. */
export const RESEARCH_USE_LABEL =
  "Sold for research use only. Not a medicine and not authorised for human consumption. Purchasers must be 18+ and confirm intended use at checkout.";
