import { EMPTY_ANSWERS, SECTION_ORDER, type AssessmentAnswers } from "@/lib/assessment/types";

/**
 * Sample answer sets for exercising the rules engine (and for UI previews).
 * They are not tests by themselves — see the engine sanity script in the
 * project notes — but they cover the three main suitability outcomes.
 */

const ALL_SECTIONS = [...SECTION_ORDER];

/** 1. Healthy 34-year-old UK woman considering semaglutide 2.4 mg weekly for weight management. */
export const healthyUkWoman: AssessmentAnswers = {
  ...EMPTY_ANSWERS,
  primaryGoal: "weight_management",
  successDescription: "Losing around 12 kg and keeping it off for a year.",
  importance: "very",
  timeframe: "3_6_months",
  consideredCompounds: [
    { slug: "semaglutide", dose: { amount: 2.4, unit: "mg", frequency: "weekly", route: "subcutaneous" } },
  ],
  currentlyTaking: "no",
  consideringMultiple: "no",
  combinations: [],
  whyChosen: "My GP mentioned it and I've read the STEP trial summaries.",
  influence: ["clinician", "research"],
  age: 34,
  sex: "female",
  heightCm: 168,
  weightKg: 84,
  unitSystem: "metric",
  countryCode: "GB",
  pregnancy: "no",
  conditions: {},
  relevantSurgery: "no",
  currentSymptoms: "no",
  takesPrescription: "no",
  prescriptions: [],
  otc: [],
  takesSupplements: "no",
  supplements: [],
  recreational: "none",
  alcohol: "occasional",
  nicotine: "none",
  previousPeptideUse: "no",
  previousUses: [],
  stoppedIneffective: "no",
  source: "uk_pharmacy",
  prescribed: "yes",
  authorisedKnown: "yes",
  qualityDocs: "yes",
  seriousAllergy: "no",
  componentAllergy: "no",
  previousSeriousReaction: "no",
  severeSymptoms: "no",
  advisedAgainst: "no",
  underInvestigation: "no",
  interactingTreatment: "no",
  reportWants: ["appropriate_to_discuss", "risks", "clinician_questions"],
  contactConsent: false,
  completedSections: ALL_SECTIONS,
  skippedSections: [],
  startedAt: "2026-09-14T08:00:00.000Z",
  completedAt: "2026-09-14T08:07:00.000Z",
  version: 1,
};

/**
 * 2. 52-year-old US man with hypertension on warfarin, considering semaglutide and
 * BPC-157 together for injury recovery, sourced from a research-chemical supplier.
 * "bpc-157" resolves once the compound database lands; until then it is reported as unresolved.
 */
export const usManWarfarin: AssessmentAnswers = {
  ...EMPTY_ANSWERS,
  primaryGoal: "injury_recovery",
  successDescription: "Getting my shoulder tendon to heal so I can train again.",
  importance: "extremely",
  timeframe: "under_1_month",
  consideredCompounds: [
    { slug: "semaglutide" },
    { slug: "bpc-157", dose: { amount: 250, unit: "mcg", frequency: "daily", route: "subcutaneous" } },
  ],
  currentlyTaking: "no",
  consideringMultiple: "yes",
  combinations: [["semaglutide", "bpc-157"]],
  whyChosen: "A training partner recommended the stack.",
  influence: ["friend", "social_media"],
  age: 52,
  sex: "male",
  heightCm: 180,
  weightKg: 96,
  unitSystem: "imperial",
  countryCode: "US",
  conditions: { hypertension: "current", cardiovascular: "none", clotting: "current" },
  relevantSurgery: "no",
  currentSymptoms: "no",
  takesPrescription: "yes",
  prescriptions: [
    {
      id: "med_warfarin",
      medicationId: "warfarin",
      name: "Warfarin",
      classId: "anticoagulant",
      strength: "5 mg",
      frequency: "daily",
      reason: "Previous DVT",
      prescribed: "yes",
    },
    {
      id: "med_ramipril",
      medicationId: "ramipril",
      name: "Ramipril",
      classId: "antihypertensive",
      strength: "10 mg",
      frequency: "daily",
      prescribed: "yes",
    },
  ],
  otc: ["painkillers"],
  takesSupplements: "yes",
  supplements: [{ id: "sup_1", name: "Creatine", amount: "5 g", frequency: "daily" }],
  recreational: "none",
  alcohol: "moderate",
  nicotine: "former",
  source: "research_supplier",
  prescribed: "no",
  authorisedKnown: "unsure",
  qualityDocs: "no",
  seriousAllergy: "no",
  componentAllergy: "no",
  previousSeriousReaction: "no",
  severeSymptoms: "no",
  advisedAgainst: "no",
  underInvestigation: "no",
  interactingTreatment: "no",
  reportWants: ["combination_evidence", "interactions", "source"],
  contactConsent: false,
  completedSections: ALL_SECTIONS.filter((s) => s !== "experience"),
  skippedSections: ["experience"],
  startedAt: "2026-09-14T09:00:00.000Z",
  completedAt: "2026-09-14T09:08:00.000Z",
  version: 1,
};

/** 3. 29-year-old pregnant person in Ireland considering semaglutide for body composition. */
export const pregnantPerson: AssessmentAnswers = {
  ...EMPTY_ANSWERS,
  primaryGoal: "fat_loss",
  successDescription: "Getting back to my pre-pregnancy shape.",
  importance: "moderate",
  timeframe: "1_3_months",
  consideredCompounds: [
    { slug: "semaglutide", dose: { amount: 0.25, unit: "mg", frequency: "weekly", route: "subcutaneous" } },
  ],
  currentlyTaking: "no",
  consideringMultiple: "no",
  combinations: [],
  influence: ["social_media"],
  age: 29,
  sex: "female",
  heightCm: 165,
  weightKg: 70,
  unitSystem: "metric",
  countryCode: "IE",
  pregnancy: "yes",
  conditions: { thyroid: "unsure" },
  relevantSurgery: "no",
  currentSymptoms: "no",
  takesPrescription: "no",
  prescriptions: [],
  otc: ["antihistamines"],
  takesSupplements: "yes",
  supplements: [{ id: "sup_folate", name: "Folic acid", amount: "400 mcg", frequency: "daily" }],
  recreational: "none",
  alcohol: "none",
  nicotine: "none",
  previousPeptideUse: "no",
  previousUses: [],
  source: "undecided",
  prescribed: "na",
  authorisedKnown: "unsure",
  qualityDocs: "unsure",
  seriousAllergy: "no",
  componentAllergy: "no",
  previousSeriousReaction: "no",
  severeSymptoms: "no",
  advisedAgainst: "no",
  underInvestigation: "no",
  interactingTreatment: "no",
  reportWants: ["risks", "appropriate_to_discuss"],
  contactConsent: true,
  contactEmail: "sample@example.com",
  contactName: "Sample",
  completedSections: ALL_SECTIONS,
  skippedSections: [],
  startedAt: "2026-09-14T10:00:00.000Z",
  completedAt: "2026-09-14T10:06:00.000Z",
  version: 1,
};

export const SAMPLE_ANSWERS = { healthyUkWoman, usManWarfarin, pregnantPerson };
